# WireGuard — outbound client tunnel to the VPS.
#
# The firewall dials the VPS (it does not listen): reusing the OPNsense WG0
# keypair means the VPS peer config is unchanged at cutover.
#
#   firewall  10.13.13.2  <-- wg -->  10.13.13.1  VPS (wireguard.yomitosh.media)
#
# The private key lives in nix-secrets at hosts/firewall/default.enc.yaml
# (key wireguard/privateKey), encrypted to the dedicated &firewall age key.
{config, ...}: {
  sops.secrets."wireguard/privateKey" = {};

  # The wg-quick unit (generated by networking.wg-quick) only declares
  # After=network-online.target, not After=unbound.service. systemd starts
  # them in parallel after network is online; wg-quick then tries to resolve
  # the endpoint hostname before Unbound has bound :53 and fails with
  # "Name or service not known". Make DNS readiness a hard prerequisite.
  systemd.services.wg-quick-wg0 = {
    after = ["unbound.service"];
    wants = ["unbound.service"];
  };

  networking.wg-quick.interfaces.wg0 = {
    address = ["10.13.13.2/32"];
    privateKeyFile = config.sops.secrets."wireguard/privateKey".path;

    # MSS clamping for the tunnel lives in nftables.nix.
    peers = [
      {
        # YHLD-VPSR1 WireGuard server, reusing the legacy vps-arm64 keypair.
        publicKey = "5zyIMCJ0eeTmXP/QrqnM7JmkZPN77PpU2u+dMazyzi4=";
        allowedIPs = ["10.13.13.0/24"];
        endpoint = "194.9.62.17:42773";
        persistentKeepalive = 25;
      }
    ];
  };
}
