# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wezterm = {
    pname = "wezterm";
    version = "0b50725f67154664292d83681f3f421c6567e3b5";
    src = fetchFromGitHub {
      owner = "wez";
      repo = "wezterm";
      rev = "0b50725f67154664292d83681f3f421c6567e3b5";
      fetchSubmodules = true;
      sha256 = "sha256-VR2QxlwwxGKH1glMkJPLlgLDWWGlFLrwrwUcmPKnxsc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-0b50725f67154664292d83681f3f421c6567e3b5/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.3.0" = "sha256-fTpJ6uNhjmCWv7dZqVgYuS2Uic36XNYTbqlaly5QBjI=";
        "sqlite-cache-0.1.3" = "sha256-sBAC8MsQZgH+dcWpoxzq9iw5078vwzCijgyQnMOWIkk=";
      };
    };
    date = "2024-05-06";
  };
}
