http:
  routers:
    adguard:
      entryPoints:
        - web
      rule: Host(`adguard.{{env "MEDIA_DOMAIN_NAME"}}`)
      middlewares:
        - https_redirect
      service: adguard
    adguard-secure:
      entryPoints:
        - websecure
      rule: Host(`adguard.{{env "MEDIA_DOMAIN_NAME"}}`)
      tls:
        certResolver: letsencrypt
      service: adguard

  services:
    adguard:
      loadBalancer:
        servers:
          # Firefly backend
          - url: "http://localhost:3005"
          # - url: "http://localhost:8077"
