http:
  routers:
    astrysk-ollama-testflight:
      entryPoints:
        - web
      rule: Host(`astrysk-ollama-testflight.duckdns.org`)
      middlewares:
        - https_redirect
      service: astrysk-ollama-testflight
    astrysk-ollama-testflight-secure:
      entryPoints:
        - websecure
      rule: Host(`astrysk-ollama-testflight.duckdns.org`)
      tls:
        certResolver: letsencrypt-duckdns
      service: astrysk-ollama-testflight

  services:
    astrysk-ollama-testflight:
      loadBalancer:
        servers:
          # Backend
          - url: https://ollama-testflight.local.{{env "MEDIA_DOMAIN_NAME"}}
