# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];

  boot.kernelPackages = pkgs.linuxPackages_6_8; # or pkgs.linuxPackages_latest
  boot.kernelParams = ["mem_sleep_default=deep"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  # boot.extraModprobeConfig = ''
  # '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f6d7f4c9-8e91-493c-bdc8-365687614175";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5cbd9301-3397-4942-adf0-96b133f48261".device = "/dev/disk/by-uuid/5cbd9301-3397-4942-adf0-96b133f48261";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0E8D-0219";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/66b3382d-d414-4b45-b910-a63eba59676c";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Power
  powerManagement.enable = true;
  # services.thermald.enable = true;

  # Button/Switch behaviours
  services.logind = {
    powerKey = "suspend";
    lidSwitch = "suspend";
    lidSwitchExternalPower = "suspend";
    lidSwitchDocked = "ignore";
  };

  # Undervolt
  services.undervolt = {
    enable = true;

    coreOffset = -85;
    gpuOffset = -85;
  };
}
